"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false
palette = "catppuccin_mocha"

format = """
$directory\
$git_branch\
$git_state
$character"""

right_format = """
$jobs\
$cmd_duration\
$nodejs\
$python\
$c\
$lua"""

[character]
success_symbol = "[󰄛 ❯](lavender)"
error_symbol = "[󰄛 ❯](red)"
vimcmd_symbol = "[󰄛 ❮](subtext1)"

[directory]
truncation_length = 4
style = "bold lavender"

[git_branch]
style = "bold mauve"

[git_state]
style = "bold yellow"
format = '\([$state( $progress_current/$progress_total)](bold yellow)\) '
rebase = "REBASE"
merge = "MERGE"
cherry_pick = "PICK"
bisect = "BISECT"
am = "AM"
am_or_rebase = "AM/REBASE"


[cmd_duration]
min_time = 2_000
format = "[ $duration](bold overlay1)"
show_milliseconds = false

[jobs]
symbol = " "
style = "bold maroon"
number_threshold = 1
format = "[$symbol$number]($style) "

[nodejs]
format = "[ $version](bold green) "
detect_files = ["package.json", ".nvmrc", ".node-version"]
detect_folders = ["node_modules"]

[python]
format = '[ ${pyenv_prefix}${version}( \($virtualenv\))](bold yellow) '
detect_files = ["pyproject.toml", "requirements.txt", "setup.py", ".python-version", "Pipfile"]
detect_extensions = ["py"]
python_binary = ["python3", "python"]

[c]
format = "[ $version(-$name)](bold sapphire) "
detect_extensions = ["c", "h", "cpp", "hpp"]

[lua]
format = "[ $version](bold blue) "
detect_files = [".lua-version"]
detect_extensions = ["lua"]

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo  = "#f2cdcd"
pink      = "#f5c2e7"
mauve     = "#cba6f7"
red       = "#f38ba8"
maroon    = "#eba0ac"
peach     = "#fab387"
yellow    = "#f9e2af"
green     = "#a6e3a1"
teal      = "#94e2d5"
sky       = "#89dceb"
sapphire  = "#74c7ec"
blue      = "#89b4fa"
lavender  = "#b4befe"
text      = "#cdd6f4"
subtext1  = "#bac2de"
subtext0  = "#a6adc8"
overlay2  = "#9399b2"
overlay1  = "#7f849c"
overlay0  = "#6c7086"
surface2  = "#585b70"
surface1  = "#45475a"
surface0  = "#313244"
base      = "#1e1e2e"
mantle    = "#181825"
crust     = "#11111b"
