[package]
name = "dots-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "dots"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
owo-colors = "4"
